### ISSUE TITLE
Fill and generate docs

### ISSUE THREAD

**Issue by JuniorJPDJ** [FUMR/music-service-async-interface#11]
ATM I'm using [this docs format](https://pythonhosted.org/an_example_pypi_project/sphinx.html) for things which may be hard to understand without documenting.
The best would be if we fill all missing docs and add some github action to generate page from docstrings.
Github pages?

**Comment by wvffle** [comment]
Is there any standard in python like jsdoc?

**Comment by JuniorJPDJ** [comment]
Actually several.
I already linked standard I used in this repo but I'll do this again: https://pythonhosted.org/an_example_pypi_project/sphinx.html
As far as I know it's also used in official python docs.

**Comment by wvffle** [comment]
I'll add https://github.com/maet3608/splint tomorrow to the linting process then

**Comment by wvffle** [comment]
Seems like I found a better alternative https://github.com/terrencepreilly/darglint#integrations

**Comment by JuniorJPDJ** [comment]
By @wvffle in https://github.com/FUMR/music-service-async-interface/issues/25#issue-695380794:
Darglint throws error codes which can be checked there: https://github.com/terrencepreilly/darglint#error-codes

**Comment by wvffle** [comment]
> By @wvffle on #25:
> Darglint throws error codes which can be checked there: https://github.com/terrencepreilly/darglint#error-codes

You know, you could just link the comment? :D

**Comment by JuniorJPDJ** [comment]
It wouldn't do preview and probably some people wouldn't read it.
