### ISSUE TITLE
Search implementation

### ISSUE THREAD

**Issue by JuniorJPDJ** [FUMR/music-service-async-interface#14]

**Comment by divadsn** [comment]
Deezer and Tidal have a search type argument, the question is whether one generic Enum like `SearchType` can fit for future music services.

**Comment by JuniorJPDJ** [comment]
@divadsn we could do generic type `Searchable` and subclass it in tracks, albums etc
Then register `Searchable` impl. in `Session` like we do with `Object`s and `AudioQualitiy`ies

**Comment by JuniorJPDJ** [comment]
I'd like to implement it today, anyone has any insights what should be taken into account?

**Comment by wvffle** [comment]
`s/which/what/`
