### ISSUE TITLE
Write docstrings for everything

### ISSUE THREAD

**Issue by wvffle** [FUMR/music-service-async-interface#25]
Also fix all of the darglint errors. Darglint throws error codes which can be checked there: https://github.com/terrencepreilly/darglint#error-codes

**Comment by JuniorJPDJ** [comment]
IMO we don't need docstring for everything, most of things are pretty intuitive and easy to understand just by reading code.
I already tried documenting not intuitive things.

**Comment by JuniorJPDJ** [comment]
Also - is that really separate issue? #11 doesn't cover it?
